### ISSUE TITLE
Add shortcode attr - prefix/suffix to add text inside the a tag, before/after outside [ Notes ]

### ISSUE THREAD

**Issue by atelierabbey** [atelierabbey/Socialbox#13]
Can be a pipe ("|") separated list. To give each item a unique prefix. A singular will prefix each, multiple will prefix each, if the prefix is small than the total list, it will prefix as many -up to it's maximum number.

Eg.
````
[socialbox type="phone1, fax1, addr1" prefix="Phone: | Fax: "]

// Will produce

Phone: 1 (555) 555-5555
Fax: 1 (555) 555-5555
123 Te St.
Testington, VA 12345
````

**Comment by SillyCoyote** [comment]
Closed. This will be overwritten in version 3 by filters, leaving the post content cleaner. The 'render' & 'settings' attributes will take over this functions as well.
