### ISSUE TITLE
New default format [Notes]

### ISSUE THREAD

**Issue by GrayofD4** [atelierabbey/Socialbox#24]
Output creates
```
<div class="socialbox social_icons {$additionalClasses}">
    <a class="social_icon social_{slugify($name);}" data-name="{$name || $type for phone/fax/email }" data-format="{if phone/fax $unformatted}" title="{$name}" href="{$url}">{if is_link() || or is_text = $middles}</a>
    ...
</div>
```

#### Benefits
   - Less markup
   - Can add ::before or ::after with data values
   - CSS driven to add BG color, Icon, width. height, hover color, etc.
   -

**Comment by SillyCoyote** [comment]
This isn't necessarily a bad idea, divs tend to have less default styling than ul/li schemes.

**Comment by SillyCoyote** [comment]
This also solves issue #14 ... so it's looking probably, at least as an alternative default 'render' setting.
