### ISSUE TITLE
Incorporate filters [Notes]

### ISSUE THREAD

**Issue by GrayofD4** [atelierabbey/Socialbox#27]
output = text, link, single, icons, svg, fa (font-awesome), etc. 
type = phone, email, fax, addr,  facebook, google-plus, etc.
link / data = URL, phone number, etc.

can modify output through filters, Link stays the same

````

function my_custom_icon( $slug, $link, $middle ) {
   $output = "<div class=.icon-{$slug}><a href={$link}>{$middle}</a></div>"
   return $output;
} add_filter('socialbox_output', 'my_custom_icon', 0, 3);
````

**Comment by SillyCoyote** [comment]
Filters? You don't say... Well, looks like version 3 solves another . 

(It's great to see early evolution of this idea...)
